---
title: Sample
---
classDiagram
    class Circle {
        - double radius
        + Circle(double r)
        + double area()
    }

    class Rectangle {
        - int width
        - int height
        + Rectangle(int x, int y)
        + int area()
    }