classDiagram
    class Fraction {
        - int numerateur
        - int denominateur
        + Fraction()
        + Fraction(int n, int d)
        + void setNumerateur(int n)
        + void setDenominateur(int d)
        + int getNumerateur()
        + int getDenominateur()
        + Fraction add(Fraction f)
        + Fraction minus(Fraction f)
        + Fraction multiply(Fraction f)
        + Fraction multiply(int n)
        + Fraction divide(Fraction f)
        + void simplify()
    }